In [1]:
from pathlib import Path

import pandas as pd

In [6]:
DATA_PATH = Path(
    "data/raw/aa_dataset-tickets-multi-lang-5-2-50-version.csv"
)

In [8]:
 df = pd.read_csv(DATA_PATH)

In [12]:
df.shape

(28587, 16)

In [15]:
df.columns.tolist()

['subject',
 'body',
 'answer',
 'type',
 'queue',
 'priority',
 'language',
 'version',
 'tag_1',
 'tag_2',
 'tag_3',
 'tag_4',
 'tag_5',
 'tag_6',
 'tag_7',
 'tag_8']

In [14]:
df.head()

,subject,body,answer,type,queue,priority,language,version,tag_1,tag_2,tag_3,tag_4,tag_5,tag_6,tag_7,tag_8
0,Wesentlicher Sicherheitsvorfall,"Sehr geehrtes Support-Team,\n\nich möchte eine...",Vielen Dank für die Meldung des kritischen Sic...,Incident,Technical Support,high,de,51,Security,Outage,Disruption,Data Breach,NaN,NaN,NaN,NaN
1,Account Disruption,"Dear Customer Support Team,\n\nI am writing to...","Thank you for reaching out, <name>. We are awa...",Incident,Technical Support,high,en,51,Account,Disruption,Outage,IT,Tech Support,NaN,NaN,NaN
2,Query About Smart Home System Integration Feat...,"Dear Customer Support Team,\n\nI hope this mes...",Thank you for your inquiry. Our products suppo...,Request,Returns and Exchanges,medium,en,51,Product,Feature,Tech Support,NaN,NaN,NaN,NaN,NaN
3,Inquiry Regarding Invoice Details,"Dear Customer Support Team,\n\nI hope this mes...",We appreciate you reaching out with your billi...,Request,Billing and Payments,low,en,51,Billing,Payment,Account,Documentation,Feedback,NaN,NaN,NaN
4,Question About Marketing Agency Software Compa...,"Dear Support Team,\n\nI hope this message reac...",Thank you for your inquiry. Our product suppor...,Problem,Sales and Pre-Sales,medium,en,51,Product,Feature,Feedback,Tech Support,NaN,NaN,NaN,NaN

In [18]:
df.isna().sum()

subject      3838
body            0
answer          7
type            0
queue           0
priority        0
language        0
version         0
tag_1           0
tag_2          13
tag_3         136
tag_4        3058
tag_5       14042
tag_6       22713
tag_7       26547
tag_8       28022
dtype: int64

In [19]:
df.duplicated().sum()

np.int64(0)

In [20]:
df.duplicated(subset=["subject", "body"]).sum()

np.int64(0)

In [21]:
(df["language"] == "en").sum()

np.int64(16338)

In [23]:
df["queue"].value_counts(normalize=True)

queue
Technical Support                  0.292511
Product Support                    0.183720
Customer Service                   0.149299
IT Support                         0.120090
Billing and Payments               0.097527
Returns and Exchanges              0.050268
Service Outages and Maintenance    0.040158
Sales and Pre-Sales                0.032112
Human Resources                    0.020149
General Inquiry                    0.014167
Name: proportion, dtype: float64

In [24]:
df_en = df[df["language"] == "en"].copy()

In [25]:
df_en.shape

(16338, 16)

In [28]:
df_en["queue"].unique()

<StringArray>
[              'Technical Support',           'Returns and Exchanges',
            'Billing and Payments',             'Sales and Pre-Sales',
 'Service Outages and Maintenance',                 'Product Support',
                      'IT Support',                'Customer Service',
                 'Human Resources',                 'General Inquiry']
Length: 10, dtype: str

In [27]:
df_en["queue"].value_counts()

queue
Technical Support                  4737
Product Support                    3073
Customer Service                   2410
IT Support                         1942
Billing and Payments               1595
Returns and Exchanges               820
Service Outages and Maintenance     664
Sales and Pre-Sales                 513
Human Resources                     348
General Inquiry                     236
Name: count, dtype: int64

In [29]:
df_en["queue"].value_counts(normalize=True)

queue
Technical Support                  0.289938
Product Support                    0.188089
Customer Service                   0.147509
IT Support                         0.118864
Billing and Payments               0.097625
Returns and Exchanges              0.050190
Service Outages and Maintenance    0.040641
Sales and Pre-Sales                0.031399
Human Resources                    0.021300
General Inquiry                    0.014445
Name: proportion, dtype: float64

In [31]:
tickets = df_en[
    ["subject", "body", "queue"]
].copy()

In [32]:
tickets.head()

,subject,body,queue
1,Account Disruption,"Dear Customer Support Team,\n\nI am writing to...",Technical Support
2,Query About Smart Home System Integration Feat...,"Dear Customer Support Team,\n\nI hope this mes...",Returns and Exchanges
3,Inquiry Regarding Invoice Details,"Dear Customer Support Team,\n\nI hope this mes...",Billing and Payments
4,Question About Marketing Agency Software Compa...,"Dear Support Team,\n\nI hope this message reac...",Sales and Pre-Sales
5,Feature Query,"Dear Customer Support,\n\nI hope this message ...",Technical Support

In [45]:
#missing subjects

tickets["subject"].isna().sum()

np.int64(0)

In [46]:
tickets["body"].isna().sum()

np.int64(0)

In [47]:
tickets["subject"] = tickets["subject"].fillna("")

In [48]:
#Create the actual text the model will read

tickets["text"] = (
    tickets["subject"]
    + " "
    + tickets["body"]
)

In [49]:
tickets[["subject", "body", "text", "queue"]].head()

,subject,body,text,queue
1,Account Disruption,"Dear Customer Support Team,\n\nI am writing to...","Account Disruption Dear Customer Support Team,...",Technical Support
2,Query About Smart Home System Integration Feat...,"Dear Customer Support Team,\n\nI hope this mes...",Query About Smart Home System Integration Feat...,Returns and Exchanges
3,Inquiry Regarding Invoice Details,"Dear Customer Support Team,\n\nI hope this mes...",Inquiry Regarding Invoice Details Dear Custome...,Billing and Payments
4,Question About Marketing Agency Software Compa...,"Dear Support Team,\n\nI hope this message reac...",Question About Marketing Agency Software Compa...,Sales and Pre-Sales
5,Feature Query,"Dear Customer Support,\n\nI hope this message ...","Feature Query Dear Customer Support,\n\nI hope...",Technical Support

In [50]:
tickets[["text", "queue"]].isna().sum()

text     0
queue    0
dtype: int64

In [51]:
tickets.shape

(16338, 4)

In [55]:
OUTPUT_PATH = Path("/Users/rinkuta/Projects/support-ticket-ai-copilot/data/processed/tickets_en.csv")

tickets.to_csv(
    OUTPUT_PATH,
    index=False
)

In [56]:
OUTPUT_PATH.exists()

True

data/raw/
    original dataset
    
data/processed/
    tickets_en.csv

## Data inspection summary

- Original dataset: 28,587 tickets
- Languages: English and German
- Modeling subset: English only
- Target: queue
- Input: subject + body
- Missing subjects are replaced with empty strings
- No duplicate tickets were found
- The target contains multiple support queues and is imbalanced